osx_image: xcode7
language: objective-c
cache:
  - bundler
  - cocoapods
install:
  - "bundle install"
  - "travis_wait bundle exec pod install"
xcode_workspace: MacDown.xcworkspace
xcode_scheme: MacDown
